<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>MeowSci.InanimateCarbonRodLib</AssemblyName>
    <RootNamespace>MeowSci.InanimateCarbonRodLib</RootNamespace>
    <Description>Example lib</Description>
    <PackageId>MeowSci.InanimateCarbonRodLib</PackageId>
  </PropertyGroup>

  <ItemGroup>
    
  </ItemGroup>


</Project>
