<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>MeowSci.UnladenSwallowLib</AssemblyName>
    <RootNamespace>MeowSci.UnladenSwallowLib</RootNamespace>
    <Description>HTTP RPC server library for the unladen-swallow KSA mod</Description>
    <PackageId>MeowSci.UnladenSwallowLib</PackageId>
    <PrunePackageReference>false</PrunePackageReference>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ksa-abstractions.lib\ksa-abstractions.lib.csproj" />
    <ProjectReference Include="..\glass.lib\glass.lib.csproj" />
    <ProjectReference Include="..\blinky.lib\blinky.lib.csproj" />
    <ProjectReference Include="..\camera-controller-override.lib\camera-controller-override.lib.csproj" />
    <ProjectReference Include="..\garrys-torch.lib\garrys-torch.lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GenHTTP.Core" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.Conversion" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.Functional" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.Layouting" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.Practices" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.Security" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.ErrorHandling" Version="10.5.0" />
    <PackageReference Include="GenHTTP.Modules.IO" Version="10.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Brutal.Core.Common" Condition="Exists('$(KSAFolder)Brutal.Core.Common.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.Core.Numerics" Condition="Exists('$(KSAFolder)Brutal.Core.Numerics.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Numerics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.ImGui" Condition="Exists('$(KSAFolder)Brutal.ImGui.dll')">
      <HintPath>$(KSAFolder)Brutal.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.ImGui.Abstractions" Condition="Exists('$(KSAFolder)Brutal.ImGui.Abstractions.dll')">
      <HintPath>$(KSAFolder)Brutal.ImGui.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.Core.Strings" Condition="Exists('$(KSAFolder)Brutal.Core.Strings.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Strings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="KSA" Condition="Exists('$(KSAFolder)KSA.dll')">
      <HintPath>$(KSAFolder)KSA.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
