<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><RequiresKSAAssemblies>false</RequiresKSAAssemblies></PropertyGroup>
  <ItemGroup><ProjectReference Include="../unscience-contracts.lib/unscience-contracts.lib.csproj" /></ItemGroup>
  <ItemGroup>
    <Compile Include="../zippo.lib/DiscoTiming.cs" Link="FeatureAlgorithms/DiscoTiming.cs" />
    <Compile Include="../graffiti.lib/SprayCadence.cs" Link="FeatureAlgorithms/SprayCadence.cs" />
    <Compile Include="../pebbles.lib/Models/*.cs" Link="Pebbles/%(Filename)%(Extension)" />
    <Compile Include="../pebbles.lib/Workshop/WorkshopMath.cs" Link="Pebbles/WorkshopMath.cs" />
    <Compile Include="../pebbles.lib/Workshop/WorkshopState.cs" Link="Pebbles/WorkshopState.cs" />
  </ItemGroup>
</Project>
