<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <!-- <TargetFramework>net10.0</TargetFramework> -->
    <AssemblyName>byo-music</AssemblyName>
    <!-- <LangVersion>13</LangVersion> -->
    <Nullable>enable</Nullable>
    <!-- <ImplicitUsings>disable</ImplicitUsings> -->
    <!-- <GenerateDocumentationFile>false</GenerateDocumentationFile> -->
    <!-- <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> -->
    <DistDir>C:\Program Files\Kitten Space Agency\Content\byo-music\</DistDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StarMap.API" Version="0.3.6" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Brutal.Core.Common" Condition="Exists('$(KSAFolder)Brutal.Core.Common.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.Core.Numerics"
      Condition="Exists('$(KSAFolder)Brutal.Core.Numerics.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Numerics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.ImGui" Condition="Exists('$(KSAFolder)Brutal.ImGui.dll')">
      <HintPath>$(KSAFolder)Brutal.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.ImGui.Abstractions"
      Condition="Exists('$(KSAFolder)Brutal.ImGui.Abstractions.dll')">
      <HintPath>$(KSAFolder)Brutal.ImGui.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.Core.Strings"
      Condition="Exists('$(KSAFolder)Brutal.Core.Strings.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Strings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="KSA" Condition="Exists('$(KSAFolder)KSA.dll')">
      <HintPath>$(KSAFolder)KSA.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="mod.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Music\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopyCustomContent" AfterTargets="AfterBuild">

    <MakeDir Directories="$(DistDir)" />
    <ItemGroup>
      <FilesToCopy Include="$(TargetDir)Assets.xml" />
      <FilesToCopy Include="$(TargetDir)mod.toml" />
      <FilesToCopy Include="$(TargetDir)$(AssemblyName).dll" />
      <FilesToCopy Include="$(TargetDir)$(AssemblyName).pdb" />
      <FilesToCopy Include="$(TargetDir)$(AssemblyName).deps.json" />
    </ItemGroup>
    <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(DistDir)" />

    <MakeDir Directories="$(DistDir)Music" />
    <ItemGroup>
      <MusicFiles Include="$(TargetDir)Music\**\*" />
      <MusicFiles Include="$(TargetDir)Music\**\*.mp3" />
    </ItemGroup>
    <Copy SourceFiles="@(MusicFiles)" DestinationFolder="$(DistDir)Music\%(RecursiveDir)" />

  </Target>

</Project>