name = "unladen-swallow"
description = "unladen-swallow"
version = "0.1.0"
author = "meow sci"

[StarMap]
EntryAssembly = "MeowSci.UnladenSwallow"

# [[StarMap.ModDependencies]]
# ModId = "blinky"
# Optional = false
# ImportedAssemblies = [
#     "MeowSci.BlinkyLib"
# ]

[[StarMap.ModDependencies]]
ModId = "zippo"
Optional = true
ImportedAssemblies = [
    "MeowSci.ZippoLib"
]